version: '3.8'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - monitoring
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./configs/loki.yaml:/etc/loki/local-config.yaml

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    networks:
      - monitoring
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./configs/promtail.yaml:/etc/promtail/config.yml
      - /var/log:/var/log

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    ports:
      - "3200:3200"   # tempo http
      - "9095:9095"   # tempo grpc
      - "14268:14268" # jaeger ingest
      - "4318:4318"   # otlp http
      - "4317:4317"   # otlp grpc
    command: -config.file=/etc/tempo/config.yaml
    networks:
      - monitoring
    volumes:
      - ./configs/tempo.yaml:/etc/tempo/config.yaml

networks:
  monitoring:
    driver: bridge
